language: python
python:
  - "2.7"
  - "3.3"
before_install:
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# command to install dependencies
install:
  - python setup.py dev
# command to run tests
script:
  - coverage run setup.py test
  - coverage report --include='upaypal_recv*' --fail-under=100
